repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v2.3.1'
  hooks:
    - id: mypy
      additional_dependencies: ['robotframework', 'testcontainers[generic]', 'robotframework-assertion-engine']
      files: ^src/
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.12.5
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.4
  hooks:
    - id: ruff-check
    - id: ruff-format
