[project]
name = "robotframework-testcontainers"
version = "0.2.1"
description = "Robot Framework keywords for Testcontainers."
readme = "README.md"
authors = [{ name = "Andreas Finkler", email = "andi.finkler@gmail.com" }]
license = "MIT"
license-file = "LICENSE"
keywords = [
  "robotframework",
  "testing",
  "test",
  "automation",
  "container",
  "testcontainers",
  "docker",
]
requires-python = ">=3.10"
dependencies = [
  "robotframework>=7.3.2",
  "robotframework-assertion-engine>=5.0.1",
  "testcontainers[generic]>=4.15.0",
]
classifiers = [
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Testing :: Mocking",
]

[project.urls]
Repository = "https://github.com/DudeNr33/robotframework-testcontainers"
Documentation = "https://dudenr33.github.io/robotframework-testcontainers/"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "7 days"
audit.malware-check = true

[tool.uv.build-backend]
module-name = "TestcontainersLibrary"
module-root = "src"

[dependency-groups]
dev = [
  "mypy>=2.3.0",
  "pre-commit>=4.3.0",
  "robotframework-requests>=0.9.7",
  "ruff>=0.14.2",
  "robotcode[all]>=2.0.1",
  "testcontainers[cockroachdb,redis]>=4.13.2",
]

[tool.mypy]
ignore_missing_imports = true
strict = true
